package com.postang.model;

public class Constants {
	public static final double SINGLEROOMFARE = 0.10;
	public static final double DOUBLEROOMFARE = 0.20;
	public static final double STANDARDROOMFARE = 0.20;
	public static final double SUITEROOMFARE = 0.25;
	public static final double ACROOMFARE = 0.25;
	public static final double NONACROOMFARE = 0.25;
	public static final String AGE_INSUFF = "Age is not sufficient";
	public static final String USERNAME_TAKEN = "Username is already taken";
	public static final String CUSTOMER = "Customer";
	public static final String ADMIN = "Admin";
	public static final String EMPLOYEE = "Employee";
	public static final String USER_INVALID = "User is Invalid.";
	public static final String INVALID = "Invalid details";
	public static final String FRM_ADR = "fromAddress";
	public static final String FRM_PWD = "fromPass";
	public static final String MAIL_SUCCESS = "Mail sent successfully";
	public static final String OTP_MAIL_SENT = "An OTP has been sent to your registered mail Id.";
	public static final String INVALID_MAIL = "Invalid Mail Address";
	public static final int MIN_RAND = 100000;
	public static final int MAX_RAND = 999999;
	public static final String TRUE = "true";
	public static final String VALID_OTP = "OTP is valid";
	public static final String INVALID_OTP = "OTP is invalid";
	public static final String EXPIRED_OTP = "OTP has been expired";
	public static final String PWD_RESET_SUCCESS = "Password Reset Success";
	public static final String PWD_RESET_FAILURE = "Password Reset Failure";
	public static final String CUST_LOG_SUCCESS = "Customer Login Success";
	public static final String EMP_LOG_SUCCESS = "Employee Login Success";
	public static final String ADM_LOG_SUCCESS = "Admin Login Success";
	public static final String NO_USER_WITH_GIVEN_NAME = "There is no user with given userName.";
	public static final String OTPMAIL = "otpMail";
	public static final String SIGNUPMAIL = "signUpMail";
	public static final String SINGUP_MAIL_SUCCESS = "Sign Up mail has been sent";
	public static final String MAIL_USERNAME = "#userName#";
	public static final String MAIL_OTP = "#OTP#";
	public static final String MAIL_CUSTNAME = "#custName#";
}
